name: Publish packages
on:
  push:
    branches:
      - main
jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - run: pnpm install
      - run: pnpm turbo pack
      - run: pnpm run publish-packages

